import { useState } from 'react'
import { ArrowUpRight, Menu, Terminal } from 'lucide-react'
import { missions as missionData, tools } from './data.js'
import Scene3D from './Scene3D.jsx'
import { profile as seedProfile } from './data.js'

const missions = (() => { try { return (JSON.parse(localStorage.getItem('qa-portfolio-content-v2'))?.missions || missionData).map(item => [item.id, item.type, item.title, item.name, item.metric]) } catch { return missionData.map(item => [item.id, item.type, item.title, item.name, item.metric]) } })()
const profile = (() => { try { return JSON.parse(localStorage.getItem('qa-portfolio-content-v2'))?.profile || seedProfile } catch { return seedProfile } })()

export default function App(){
  const [open,setOpen]=useState(false)
  return <div className="min-h-screen bg-[#07100f] text-[#e9f4df] selection:bg-[#c9f36b] selection:text-[#07100f]"><a href="/blog" className="fixed bottom-6 right-6 z-20 rounded-full border border-[#c9f36b] bg-[#07100f] px-4 py-3 font-mono text-sm text-[#c9f36b] shadow-[0_0_20px_#c9f36b33]">Blog ↗</a>
    <header className="sticky top-0 z-10 border-b border-[#1b3831]/80 bg-[#07100f]/90 backdrop-blur"><nav className="mx-auto flex h-20 max-w-6xl items-center justify-between px-6"><a href="#top" className="font-mono text-xl font-bold"><span className="text-[#c9f36b]">&gt;_</span> MINH<span className="text-[#c9f36b]">.</span></a><button className="md:hidden" onClick={()=>setOpen(!open)}><Menu/></button><div className={`${open?'flex':'hidden'} absolute left-0 top-20 w-full flex-col gap-5 bg-[#07100f] p-6 md:static md:flex md:w-auto md:flex-row md:bg-transparent`}><a href="#profile">Profile</a><a href="#missions">Projects</a><a href="#toolkit">Toolkit</a><a href="#contact" className="text-[#c9f36b]">[ hire_me ] ↗</a></div></nav></header>
    <main id="top" className="mx-auto max-w-6xl px-6"><section className="grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="font-mono text-xs tracking-widest text-slate-400"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#c9f36b] shadow-[0_0_12px_#c9f36b]"/>SYSTEM ONLINE · AVAILABLE FOR WORK</p><h1 className="my-7 text-6xl font-bold leading-[.92] tracking-[-.08em] md:text-8xl">Breaking bugs.<br/><em className="text-[#c9f36b]">Building trust.</em></h1><p className="max-w-lg text-lg leading-relaxed text-slate-400">QA Engineer chuyên kiểm thử phần mềm, tự động hóa quy trình và biến những edge case thành trải nghiệm đáng tin cậy.</p><div className="mt-8 flex gap-3"><a href="#missions" className="rounded bg-[#c9f36b] px-5 py-3 font-bold text-[#07100f]">Xem năng lực <ArrowUpRight className="inline" size={16}/></a><a href="#contact" className="rounded border border-[#1b3831] px-5 py-3">Kết nối</a></div></div><div className="group relative h-[430px] overflow-hidden rounded-xl border border-[#244b40] bg-[#0d211c] shadow-[0_0_80px_#55e5c012]"><Scene3D/><div className="pointer-events-none absolute left-5 top-5 font-mono text-[10px] text-[#55e5c0]">3D QUALITY CORE / LIVE</div><div className="pointer-events-none absolute bottom-5 right-5 font-mono text-[10px] text-slate-500">DRAG TO INSPECT ↗</div></div></section>
    <section id="profile" className="border-t border-[#1b3831] py-28"><p className="font-mono text-xs text-[#c9f36b]">01 / profile</p><div className="mt-10 grid gap-10 md:grid-cols-2"><h2 className="text-5xl font-bold leading-none tracking-[-.07em] md:text-6xl">I don't just find bugs.<br/>I protect <em className="text-[#c9f36b]">quality.</em></h2><p className="text-lg leading-relaxed text-slate-400">QA Engineer với tư duy của một người dùng khó tính và kỹ năng của một builder. Mình thiết kế test case, xây automation và giúp team release tự tin hơn.</p></div></section>
    <section id="missions" className="py-20"><p className="font-mono text-xs text-[#c9f36b]">02 / selected missions</p><div className="mt-10 grid gap-4 md:grid-cols-3">{missions.map(([n,type,title,name,metric])=><article key={n} className="rounded-lg border border-[#1d493d] bg-[#0d211c] p-5 transition hover:-translate-y-1 hover:border-[#c9f36b]"><div className="flex justify-between font-mono text-xs text-slate-400"><span>{n} — {type}</span><span className="text-[#55e5c0]">● PASSED</span></div><div className="my-5 flex h-64 items-center justify-center rounded bg-[#102e27] text-center text-3xl font-bold tracking-tighter"><span>{title}</span></div><div className="flex justify-between"><b>{name}</b><span className="font-mono text-xs text-[#c9f36b]">{metric}</span></div></article>)}</div></section>
    <section id="toolkit" className="border-t border-[#1b3831] py-28"><p className="font-mono text-xs text-[#c9f36b]">03 / toolkit</p><div className="mt-8 flex flex-col justify-between gap-5 md:flex-row"><h2 className="text-5xl font-bold leading-none tracking-[-.07em]">The stack behind<br/><em className="text-[#c9f36b]">the quality.</em></h2><p className="max-w-sm text-slate-400">Built with real tools, tested with intent.</p></div><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{tools.map(([icon,name,desc,score])=><div key={name} className="group relative rounded border border-[#1b3831] bg-[#0d1a18] p-4 transition hover:-translate-y-1 hover:border-[#c9f36b] hover:shadow-[0_0_24px_#c9f36b33]"><span className="mb-8 grid h-10 w-10 place-items-center rounded bg-[#17352d] font-mono text-lg text-[#c9f36b]">{icon}</span><b>{name}</b><small className="mt-2 block font-mono text-[10px] text-slate-500">{desc}</small><strong className="absolute bottom-3 right-4 font-mono text-xs text-[#c9f36b]">{score}</strong></div>)}</div></section>
    <section id="contact" className="grid gap-10 border-t border-[#1b3831] py-28 md:grid-cols-2"><div><p className="font-mono text-xs text-[#c9f36b]">04 / contact</p><h2 className="mt-7 text-5xl font-bold leading-none tracking-[-.07em] md:text-6xl">Ready to ship<br/><em className="text-[#c9f36b]">better software?</em></h2></div><div className="self-end"><p className="font-mono text-slate-400">// Let's make your next release bulletproof.</p><a className="mt-6 inline-block border-b-2 border-[#c9f36b] text-2xl" href="mailto:hello@minhnguyen.dev">hello@minhnguyen.dev ↗</a><div className="mt-12 flex gap-5 text-slate-400"><a href="#">GitHub</a><a href="#">LinkedIn</a><Terminal/></div></div></section></main><footer className="border-t border-[#1b3831] px-6 py-7 text-center font-mono text-xs text-slate-500">© 2024 MINH NGUYEN // QA ENGINEER</footer></div>
}
